MODEL:
  META_ARCHITECTURE: SSLMetaArch
  DEVICE: cuda
  WEIGHTS: ''
  DTYPE: float32
compute_precision:
  param_dtype: bf16
  reduce_dtype: fp32
  sharding_strategy: SHARD_GRAD_OP
dino:
  loss_weight: 1.0 
  global_ignore_diagonal: true
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_norm_last_layer: false
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
  koleo_loss_distributed: false
  koleo_topk: 1
  koleo_distributed_replicas: 0
  force_weight_norm: false
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max: 
  - 0.1
  - 0.5
  mask_random_circular_shift: false
  force_masking_even_with_zero_weight: false
  separate_head: true
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_norm_last_layer: false
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  batch_size_per_gpu: 64  # Effective global batch = 8*64 = 512
  dataset_path: ImageFolder:split=TRAIN # you should override this with CLI command
  output_dir: <OUTPUT_DIR>
  seed: 0
  num_workers: 10
  cache_dataset: true # if true, shard fixed subsets of dataset to each GPU
  # controls when training steps/LR, warmup, momentum schedules so make sure to set correctly
  OFFICIAL_EPOCH_LENGTH: 1220 # steps/epoch ≈ ceil(624461 / 512) = 1220 
  monitor_gradient_norm: false
  chunk_schedule: []
  use_teacher_head: true 
  learn_from_teacher_tokens: false
  centering: sinkhorn_knopp
  saveckp_freq: 1
  compile: true
  checkpointing: false # gradient checkpointing, not model checkpointing :skull:
  compile: true
  cudagraphs: false
  cell_augmentation: false
student:
  arch: vit_large
  patch_size: 16
  in_chans: 1
  drop_path_rate: 0.3
  layerscale: 1.0e-05
  patch_drop: 0.0
  ffn_layer: "mlp"
  ffn_ratio: 4
  resume_from_teacher_chkpt: "path to vit satl checkpoint here"
  resume_from_teacher_chkpt_skip_load_keys:
    - "storage_tokens"
    - "local_cls_norm"
    - "qkv.bias_mask"
  resume_from_teacher_chkpt_keys_not_sharded: []
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  norm_layer: layernormbf16
  n_storage_tokens: 0
  mask_k_bias: false
  pos_embed_type: rope
  pos_embed_rope_base: 100.0
  pos_embed_rope_min_period: null
  pos_embed_rope_max_period: null
  pos_embed_rope_normalize_coords: separate  # min, max, separate
  pos_embed_rope_shift_coords: null
  pos_embed_rope_jitter_coords: null
  pos_embed_rope_rescale_coords: null
  pos_embed_rope_dtype: bf16
  fp8_enabled: False  # Convert Linear layers to operate in fp8 precision
  fp8_filter: "blocks"  # Regex that must appear in module path; empty means everything
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1.0
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
  in_chans: 1
distillation:
  enabled: false
  full_cfg_path: ''
  checkpoint_path: ''
multidistillation:
  enabled: false
hrft:
  enabled: false
  checkpoint_path: ''
optim:
  epochs: 100
  optimizer: adamw
  lr: 0.0003
  warmup_epochs: 10
  min_lr: 1.0e-06
  weight_decay: 0.04
  weight_decay_end: 0.4
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  multi_tensor_optim: true
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crops_size: 256
  local_crops_size: 112
  local_crops_number: 8
  global_crops_scale: 
  - 0.32
  - 1.0
  local_crops_scale: 
  - 0.05
  - 0.32
  localcrops_subset_of_globalcrops: false
  share_color_jitter: false
  horizontal_flips: true
  rgb_mean: # Actually SAR mean but DINOv3 expects rgb_mean name
  - 0.199  
  rgb_std:
  - 0.144
checkpointing: 
  period: 1000
  max_to_keep: 3


